-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 12:38:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Alumnos` (
  `DNI_Al` VARCHAR(9) NOT NULL,
  `Nombre_Al` VARCHAR(45) NOT NULL,
  `Apellido1_Al` VARCHAR(45) NOT NULL,
  `Apellido2_Al` VARCHAR(45) NULL,
  `Edad_Al` INT UNSIGNED NULL DEFAULT 0,
  `Telefono_Al` INT(9) NULL DEFAULT 0,
  `Direccion_Al` VARCHAR(45) NULL,
  `Ciudad_Al` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI_Al`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Profesores` (
  `DNI_P` VARCHAR(9) NOT NULL,
  `Nombre_P` VARCHAR(45) NOT NULL,
  `Apellido1_P` VARCHAR(45) NOT NULL,
  `Apellido2_P` VARCHAR(45) NULL,
  `NCuenta_P` INT(20) NULL,
  `Telefono_P` INT(9) UNSIGNED NOT NULL,
  `Especialidad_P` VARCHAR(45) NULL,
  `Direccion_P` VARCHAR(45) NULL,
  `Ciudad_P` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI_P`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Asignaturas` (
  `Codigo_As` INT UNSIGNED NOT NULL,
  `Nombre_As` VARCHAR(45) NULL,
  `Creditos_As` INT NULL DEFAULT 0,
  `Facultad_As` VARCHAR(45) NULL,
  `DNI_P` VARCHAR(9) NULL,
  PRIMARY KEY (`Codigo_As`),
  INDEX `DNI_P_idx` (`DNI_P` ASC),
  CONSTRAINT `DNI_P`
    FOREIGN KEY (`DNI_P`)
    REFERENCES `academia`.`Profesores` (`DNI_P`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Alumnos_has_Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Alumnos_has_Asignaturas` (
  `Alumnos_DNI_Al` VARCHAR(9) NOT NULL,
  `Asignaturas_Codigo_As` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Alumnos_DNI_Al`, `Asignaturas_Codigo_As`),
  INDEX `fk_Alumnos_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_Codigo_As` ASC),
  INDEX `fk_Alumnos_has_Asignaturas_Alumnos_idx` (`Alumnos_DNI_Al` ASC),
  CONSTRAINT `fk_Alumnos_has_Asignaturas_Alumnos`
    FOREIGN KEY (`Alumnos_DNI_Al`)
    REFERENCES `academia`.`Alumnos` (`DNI_Al`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_Codigo_As`)
    REFERENCES `academia`.`Asignaturas` (`Codigo_As`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
